import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { ResearchButton } from "@/components/research-button";

export default async function ProjectPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  const { data: project } = await supabase.from("projects").select("id,name,status,current_stage,created_at").eq("id", id).eq("user_id", user.id).single();
  if (!project) notFound();
  const { data: inputs } = await supabase.from("project_inputs").select("problems,goals,additional_context").eq("project_id", id).order("created_at", { ascending: true }).limit(1);
  const { data: latestRun } = await supabase.from("research_runs").select("id,status,stage,metadata,created_at,completed_at,error_message").eq("project_id", id).order("created_at", { ascending: false }).limit(1).maybeSingle();
  const { count: evidenceCount } = await supabase.from("research_evidence").select("id", { count: "exact", head: true }).eq("research_run_id", latestRun?.id ?? "00000000-0000-0000-0000-000000000000");
  return <main className="min-h-screen bg-[#f7f8fa]"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center gap-4 px-6 py-5"><Link href="/dashboard" className="text-sm text-slate-500">← Projects</Link><span className="text-slate-300">/</span><span className="font-semibold">{project.name}</span></div></header><div className="mx-auto max-w-5xl px-6 py-10"><div className="rounded-3xl border border-slate-200 bg-white p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-sm uppercase tracking-wider text-slate-400">Research project</p><h1 className="mt-2 text-3xl font-semibold">{project.name}</h1></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm capitalize text-slate-600">{project.status}</span></div><div className="mt-8 rounded-2xl bg-slate-50 p-5"><p className="text-xs font-medium uppercase tracking-wider text-slate-400">Starting point</p><p className="mt-2 leading-7 text-slate-700">{inputs?.[0]?.problems ?? "No starting point saved."}</p></div><div className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-slate-200 p-5"><p className="text-xs uppercase tracking-wider text-slate-400">Research run</p><p className="mt-2 text-lg font-semibold capitalize">{latestRun?.status ?? "Not started"}</p></div><div className="rounded-2xl border border-slate-200 p-5"><p className="text-xs uppercase tracking-wider text-slate-400">Stage</p><p className="mt-2 text-lg font-semibold">{latestRun?.stage?.replaceAll("_", " ") ?? "Ready"}</p></div><div className="rounded-2xl border border-slate-200 p-5"><p className="text-xs uppercase tracking-wider text-slate-400">Evidence</p><p className="mt-2 text-lg font-semibold">{evidenceCount ?? 0} sources</p></div></div><div className="mt-8 border-t border-slate-100 pt-8"><h2 className="text-xl font-semibold">Research engine</h2><p className="mt-2 max-w-2xl text-slate-600">ProductForge will search across demand, pain points, existing solutions, monetization signals, competition gaps and underserved needs.</p><div className="mt-5"><ResearchButton projectId={project.id} /></div></div>{latestRun?.status === "failed" && <div className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{latestRun.error_message}</div>}</div></div></main>;
}
