import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { logout } from "@/app/(auth)/actions";
import { Brand } from "@/components/brand";

export default async function DashboardPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  const { data: projects } = await supabase.from("projects").select("id,name,status,created_at").order("created_at", { ascending: false }).limit(6);
  const firstName = user.user_metadata?.full_name?.split(" ")[0] || "there";

  return <main className="min-h-screen bg-[#f5f5f2] text-[#171714]">
    <header className="sticky top-0 z-30 border-b border-[#deded7] bg-[#f5f5f2]/90 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10"><Brand href="/dashboard"/><div className="flex items-center gap-2"><Link href="/projects/new" className="rounded-full bg-[#171714] px-4 py-2.5 text-sm font-semibold text-white transition hover:-translate-y-0.5">New project →</Link><form action={logout}><button className="rounded-full px-4 py-2.5 text-sm text-[#73736d] transition hover:bg-white hover:text-[#171714]">Log out</button></form></div></div></header>
    <div className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-10 lg:py-14">
      <div className="relative overflow-hidden rounded-[32px] border border-[#deded7] bg-[#ecece6] p-7 sm:p-10 lg:p-12"><div className="pf-grid absolute inset-0 opacity-60"/><div className="relative flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#8a8a82]">Your workspace</p><h1 className="pf-display mt-3 text-5xl font-semibold leading-[.94] sm:text-6xl">Good to see you, {firstName}.</h1><p className="mt-4 max-w-xl text-sm leading-7 text-[#73736d]">Ideas, research runs and product opportunities — organized from first signal to launch.</p></div><div className="rounded-full bg-white/80 px-4 py-2 text-xs font-semibold">Evidence first</div></div></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-3">{[["Projects",projects?.length??0,"Active workspaces"],["Research mode","Evidence","Sources stay attached to insights"],["Next step",projects?.length?"Research":"Discover",projects?.length?"Continue a project":"Create your first project"]].map(([label,value,description])=><div key={label as string} className="rounded-[26px] border border-[#deded7] bg-white p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#999991]">{label}</p><p className="mt-5 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-[#73736d]">{description}</p></div>)}</div>
      <div className="mt-10"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#8a8a82]">Your projects</p><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{projects?.length ? projects.map((project)=><Link key={project.id} href={`/projects/${project.id}`} className="pf-card-hover group rounded-[28px] border border-[#deded7] bg-white p-6"><div className="flex items-start justify-between"><span className="rounded-full bg-[#f0f0eb] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-[#66665f]">{project.status??"Draft"}</span><span className="text-lg text-[#9a9a91] group-hover:translate-x-1">↗</span></div><h2 className="mt-10 text-xl font-semibold tracking-tight">{project.name}</h2><p className="mt-3 text-sm leading-6 text-[#73736d]">Continue research, inspect evidence and explore the strongest opportunities.</p><div className="mt-8 border-t border-[#ededE7] pt-4 text-xs font-semibold text-[#8a8a82]">Open workspace</div></Link>):<div className="col-span-full rounded-[30px] border border-dashed border-[#cfcfc7] bg-white p-12 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#eef5cf] text-xl">✦</div><h2 className="mt-5 text-xl font-semibold">Find your first opportunity</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-[#73736d]">Start with a skill, audience, problem or market. ProductForge will turn it into a structured research workflow.</p><Link href="/projects/new" className="mt-6 inline-flex rounded-full bg-[#171714] px-5 py-3 text-sm font-semibold text-white">Create project →</Link></div>}</div></div>
    </div>
  </main>;
}
